### ISSUE TITLE
Add support for Upserts

### ISSUE THREAD

**Issue by stevan** [vti/sql-composer#5]
I would like to add support for "Upserts" or in MySQL speak "ON DUPLICATE KEY UPDATE". Where would be the best place to add this?

- New `SQL::Composer::Upsert` class?
- Add an `upsert => 1` to the `SQL::Composer::Update` class?
- ???

Interested?

**Comment by vti** [comment]
I like a separate upsert.

**Comment by stevan** [comment]
Okay, I will put together a pull request.

**Comment by vti** [comment]
There is a driver parameter in Insert btw.

**Comment by stevan** [comment]
Might have a patch, the MySQL version is causing issues, please hold off any release or anything.

**Comment by stevan** [comment]
Thanks :)
