### ISSUE TITLE
Add `table` method to Select, Insert, Update and Delete classes

### ISSUE THREAD

**Issue by stevan** [vti/sql-composer#6]
It is sometimes useful to know from which `table` a particular query is for, in the case of `SQL::Composer::Select`, this is exposed via the `from` hash key (which is preserved in the instance), but all the other classes (Insert, Update, Delete) seem to not keep that information around anymore. 

I propose having a single unified API among the classes, just a `table` method which returns the primary table in a query. This can also be expanded for Select queries to add a `is_join` and/or `tables` methods if you like.

Thoughts?

**Comment by vti** [comment]
The idea was to use sql-like words, so you get select(from ...) and
update(table ...). But maybe a unified table method would be better.

**Comment by stevan** [comment]
I don't mind using the SQL like words in the constructor params, I think that makes it easier to remember actually, but I am talking about just having a `table` method which delegates to whatever hash key that information was put in (`into`, `from`, etc).
